version: '3.4'

services:
  MySql:
    container_name: ContinuousMigrations-MySql
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - ./sample/Infrastructure/mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: P@s5w0rd5Ar3G0OD!
    
  Web:
    image: web
    container_name: ContinuousMigrations-Web
    build:
      context: .
      dockerfile: sample/Web/Dockerfile
    ports:
      - 80
    depends_on: 
      - MySql